import { Link } from 'react-router-dom';

const AiDataPrivacy = () => {
    return (
        <div className="flex-grow flex flex-col bg-background-light dark:bg-background-dark min-h-screen">
            <div className="max-w-4xl mx-auto px-6 py-16 w-full">
                <h1 className="text-3xl sm:text-4xl font-black text-gray-900 dark:text-white mb-4">AI Data and Privacy</h1>
                <p className="text-sm sm:text-base text-gray-600 dark:text-gray-300 mb-8">
                    This page explains what data is used for AI features (chat, voice commands, narration), where it is stored,
                    and how you can control it.
                </p>

                <div className="space-y-5">
                    <section className="bg-white dark:bg-[#1e1d32] p-5 rounded-2xl border border-gray-200 dark:border-[#272546]">
                        <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">What Data Is Sent</h2>
                        <ul className="text-sm text-gray-600 dark:text-gray-300 list-disc pl-5 space-y-1">
                            <li>Your message for AI Tutor chat.</li>
                            <li>Current visualization context needed to answer your question.</li>
                            <li>Voice command text (when you use voice control).</li>
                            <li>Step descriptions for AI narration generation.</li>
                            <li>Your selected provider and API key for AI requests.</li>
                        </ul>
                    </section>

                    <section className="bg-white dark:bg-[#1e1d32] p-5 rounded-2xl border border-gray-200 dark:border-[#272546]">
                        <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Where Your API Key Is Stored</h2>
                        <p className="text-sm text-gray-600 dark:text-gray-300">
                            Your API key is stored in your browser on this device using local storage under your signed-in user profile.
                            It is not shown publicly. You can update or remove it anytime from <strong>Profile -&gt; AI Settings</strong>.
                        </p>
                    </section>

                    <section className="bg-white dark:bg-[#1e1d32] p-5 rounded-2xl border border-gray-200 dark:border-[#272546]">
                        <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Third-Party AI Processing</h2>
                        <p className="text-sm text-gray-600 dark:text-gray-300">
                            AI responses are generated by your selected provider (Gemini, Groq, or OpenAI). Their terms and privacy
                            policies apply to requests sent through their APIs.
                        </p>
                    </section>

                    <section className="bg-white dark:bg-[#1e1d32] p-5 rounded-2xl border border-gray-200 dark:border-[#272546]">
                        <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-2">Your Controls</h2>
                        <ul className="text-sm text-gray-600 dark:text-gray-300 list-disc pl-5 space-y-1">
                            <li>Disable AI Tutor or narration whenever you want.</li>
                            <li>Change provider and key in Profile settings.</li>
                            <li>Use <strong>Remove Key</strong> in Profile to delete saved credentials from this browser.</li>
                        </ul>
                    </section>

                    <section className="bg-amber-50 dark:bg-amber-500/10 p-5 rounded-2xl border border-amber-200 dark:border-amber-500/20">
                        <h2 className="text-lg font-bold text-amber-800 dark:text-amber-300 mb-2">Security Note</h2>
                        <p className="text-sm text-amber-900 dark:text-amber-200">
                            Client-side storage is convenient but not a secure vault. Do not use high-privilege or unrestricted keys.
                            Prefer scoped keys and provider-side usage limits.
                        </p>
                    </section>
                </div>

                <div className="mt-8 flex items-center gap-3 text-sm">
                    <Link to="/profile" className="text-primary font-semibold hover:underline">Go to Profile AI Settings</Link>
                    <span className="text-gray-400">|</span>
                    <Link to="/privacy" className="text-primary font-semibold hover:underline">General Privacy Policy</Link>
                </div>
            </div>
        </div>
    );
};

export default AiDataPrivacy;
